### ISSUE TITLE
Deployment on changes?

### ISSUE THREAD

**Issue by jariz** [magicspon/gatsby-starter-craftcms#1]
Hiya, as you've seem to have putten quite some thought into this setup, I was wondering what you personally use in projects with this setup to deploy gatsby itself.

Do you manually deploy it each time or do you have some kind of setup in place to auto deploy gatsby on changes to craft entries?
Information on this subject seems to be scarce, and contentful's webhooks feature seems kinda tempting.

**Comment by magicspon** [comment]
heyo...

massive sorry, i've only just seen this issue.

I used this setup on http://wearestraightline.com

we're using deployhq to manage deployments... my colleague built a plugin that would allow the client to hit a button that would send a deployment request to deployhq, which would in turn trigger a built.

if you're on netlify and using github, i believe there is a plugin that will handle that.

anyhow, apologies for the epically late response...
